version: '3'
services:
  db:
    image: postgres:16.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: product

  spring-boot-app:
      build:
        context: ./backend
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      depends_on:
        - db
      environment:
        DB_URL: jdbc:postgresql://db:5432/product
        DB_USER: postgres
        DB_PASSWORD: postgres

  react-app:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      ports:
        - "3000:80"
